function mostrarinfo(){
    let titular1 = document.getElementById("Informacion")
titular1.innerText = "Nacionalidad: Argentina" // PREGUNTAR COMO PUEDO HACER PARA QUE AL CAMBIAR EL TEXTO ME MUESTRE UNA LISTA? YO QUIERO QUE APAREZCA: INFORMACION DEL DT Y ABAJO UN BOTON MOSTRAR. TOCAR MOSTRAR Y QUE ME APAREZCA LA LISTA CON LA INFORMACION.
